name: junitreport
version: 1.2.1-dev
description: Generate JUnit XML reports from dart test runs. Transforms the output of dart or flutter tests to
  JUnit style XML

homepage: https://github.com/TOPdesk/dart-junitreport
documentation:

dependencies:
  args: ^1.5.2
  intl: ^0.16.1
  testreport: ^1.2.0
  xml: ^3.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: any

environment:
  sdk: '>=2.7.0 <3.0.0'

executables:
  tojunit: