name: junitreport
version: 0.2.2-dev
description: Generate JUnit XML reports from dart test runs.

authors:
- Roel Spilker <r.spilker@gmail.com>

homepage: https://github.com/TOPdesk/dart-junitreport
documentation:

dependencies:
  xml: '>= 2.5.0 <2.6.0'
  intl: '^0.14.0'
  testreport: '^0.2.0'
  args: '^0.13.7'

dev_dependencies:
  test: any

environment:
  sdk: '>=1.12.0 <2.0.0'

executables:
  tojunit:
