name: junitreport
version: 0.3.1
description: Generate JUnit XML reports from dart test runs.

authors:
- Roel Spilker <r.spilker@gmail.com>

homepage: https://github.com/TOPdesk/dart-junitreport
documentation:

dependencies:
  xml: '^3.0.0'
  intl: '^0.15.5'
  testreport: '^0.3.0'
  args: '^1.4.4'

dev_dependencies:
  test: any

environment:
  sdk: '>=1.19.0 <3.0.0'

executables:
  tojunit:
