name: junitreport
version: 1.0.1
description: Generate JUnit XML reports from dart test runs.

authors:
- Roel Spilker <r.spilker@gmail.com>

homepage: https://github.com/TOPdesk/dart-junitreport
documentation:

dependencies:
  xml: '^3.3.1'
  intl: '^0.15.7'
  testreport: '^1.0.0'
  args: '^1.5.1'

dev_dependencies:
  test: any

environment:
  sdk: '>=2.1.0 <3.0.0'

executables:
  tojunit:
